config/routes.rb
Rails.application.routes.draw do
devise_for :users
root to: 'books#index'
get 'books' => 'books#new', as: 'new_book'
resources :books
resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
    redirect_to book_path(@book.id), notice: 'Book was successfully destroyed.'
    else 
    render action: :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'Book was successfully destroyed.'
    else
     render action: :edit
    end
  end
    
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to new_book_path, notice: 'Book was successfully destroyed.'
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class = "bookers">
<h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
  <%= link_to 'Show', book_path(@book.id) %>
  <%= link_to 'Back', new_book_path %>
<% end %>
</div>

app/views/books/index.html.erb
<div class = 'bookers'>
    <h2>ようこそ Bookers へ！</h2>
    <h6><span>Bookers</span>では、様々な書籍に関するあなたの意見や<br>印象を共有し交換することができます</h6>

    <%= link_to 'start', new_book_path %>
  </div>
</div>

app/views/books/new.html.erb
<div class = "bookers">
<p id="notice">
 <%= notice %>
</p>

<h1>Books</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
            <tr>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
                <td><%= link_to 'Show', book_path(book.id), class:"show_#{book.id}" %></td>
                <td><%= link_to "Edit", edit_book_path(book.id), class:"edit_#{book.id}" %></td>
                <td><%= link_to 'Destroy', book_path(book.id), method: :delete, data: { confirm: "Are you sure?" }, class:"destroy_#{book.id}" %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<div class ="newbook">
  <h1>New book</h1>
　<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
　<% end %>
  <%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
  <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class = "bookers">
<p id="notice">
 <%= notice %>
</p>
 Title : <%= @book.title %>
  Body : <%= @book.body %>
<%= link_to 'Edit', edit_book_path(@book.id) %>
<%= link_to 'Back', new_book_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
      <li>
      <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= image_tag('sample-author1.jpg') %>
</div>
<% @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
    <%= attachment_image_tag post_image, :image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag('sample-author1.jpg') %></p>
  <p>ショップ名：<%= post_image.shop_name %></p>
  <p>説明：<%= post_image.caption %></p>
  <p>ユーザーネーム：<%= post_image.user.name %></p>
</div>
<% end %>
<%= paginate @post_images %>